from .auto_prompt_line import NODE_CLASS_MAPPINGS as AUTO_LINE, NODE_DISPLAY_NAME_MAPPINGS as AUTO_LINE_NAMES
from .prompt_line_loader import NODE_CLASS_MAPPINGS as PROMPT_LOADER, NODE_DISPLAY_NAME_MAPPINGS as PROMPT_LOADER_NAMES
from .simple_number_counter import NODE_CLASS_MAPPINGS as COUNTER, NODE_DISPLAY_NAME_MAPPINGS as COUNTER_NAMES
from .wildcard_prompt_assembler import NODE_CLASS_MAPPINGS as WILDCARD, NODE_DISPLAY_NAME_MAPPINGS as WILDCARD_NAMES

NODE_CLASS_MAPPINGS = {**AUTO_LINE, **PROMPT_LOADER, **COUNTER, **WILDCARD}
NODE_DISPLAY_NAME_MAPPINGS = {**AUTO_LINE_NAMES, **PROMPT_LOADER_NAMES, **COUNTER_NAMES, **WILDCARD_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]